apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
  namespace: microtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: readytofight112.azurecr.io/acrreadytofight:v1
        ports:
        - containerPort: 80




